
#-----------------------------------------------------------------------

APP       := FireKeeper
TARGET    := LobbySvr
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------

include /home/tarsproto/FireKeeper/Common/Common.mk
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
