
#-----------------------------------------------------------------------

APP       := FireKeeper
TARGET    := Common
TARGETLIB := lib${TARGET}.a
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 
PROTO_PATH := /home/tarsproto/FireKeeper/${TARGET}

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------
#命令行必须tab开头
include /usr/local/tars/cpp/makefile/makefile.tars
release2:	
	cp -rf *.h ${PROTO_PATH}
#release:
#	cp -rf *.h ${PROTO_PATH}
#	cp -rf *.tars ${PROTO_PATH}
#	echo "INCLUDE += -I${PROTO_PATH} > ${PROTO_PATH}/${TARGET}.mk"
#-----------------------------------------------------------------------
