
#-----------------------------------------------------------------------

APP       := FireKeeper
TARGET    := RoomAllocaterSvr
CONFIG    := 
STRIP_FLAG:= N
TARS2CPP_FLAG:= 

INCLUDE   += 
LIB       += 

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars
include /home/tarsproto/FireKeeper/Common/Common.mk
#-----------------------------------------------------------------------
